In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_list2 = [[1,2], [3,4], [5,6]]

In [6]:
arr2 = np.array(my_list2)

In [7]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.83211016, 0.78433093, 0.63637592, 0.66061212, 0.32104384])

In [20]:
np.random.rand(5,5)

array([[0.73272431, 0.21165848, 0.41687409, 0.19030524, 0.42527307],
       [0.94940265, 0.12188947, 0.49792842, 0.26506195, 0.40664299],
       [0.16104813, 0.37159378, 0.86838407, 0.84269006, 0.64745337],
       [0.03931836, 0.73772111, 0.35814115, 0.17386048, 0.45976572],
       [0.77745551, 0.95916063, 0.43071589, 0.86477968, 0.869943  ]])

In [21]:
np.random.randn(2)

array([-1.10376271, -0.00982425])

In [22]:
np.random.randn(2,2)

array([[-0.48616251, -0.49331193],
       [ 0.05493454, -1.2925472 ]])

In [5]:
import numpy as np
np.random.randint(1,100,10)

array([30, 20, 55, 67, 85, 53, 16, 73, 53,  5])

In [6]:
import numpy as np
arr = np.arange(25)

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr1 = np.random.randint(0,25,10)

In [33]:
arr1

array([24, 22, 10,  0, 17,  8,  3, 23, 20, 20])

In [34]:
arr1.max()

24

In [35]:
arr1.argmax()

0

In [40]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.dtype

dtype('int32')

In [47]:
att = np.arange(11)

In [48]:
att

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
att[:5]

array([0, 1, 2, 3, 4])

In [66]:
arr = np.arange(11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[0:5] = 100

In [54]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
slice_of_arr = arr[0:5]

In [61]:
slice_of_arr[:] = 100

In [62]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [63]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [67]:
arr_copy = arr.copy()

In [68]:
arr_copy[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr_copy[:5] = 100

In [70]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [80]:
arr_2d[:2,1:] #single bracket notation

array([[10, 15],
       [25, 30]])

In [82]:
bool_arr = arr > 4

In [83]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
arr[arr < 3]

array([0, 1, 2])

In [88]:
arr_2d = np.arange(50).reshape(5,10)

In [89]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])